title: Arash Kadkhodaei
description: My personal website
remote_theme: pages-themes/cayman@v0.2.0
url: "https://kadkhodaei.de"
show_downloads: false
github:
  is_project_page: false

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap